"""service foundation baseline

Revision ID: 0001_service_foundation
Revises:
Create Date: 2026-07-24 08:43:59.502373
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_service_foundation'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=120), nullable=False),
    sa.Column('trigger_type', sa.String(length=80), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('input_revision', sa.String(length=160), nullable=False),
    sa.Column('queued_count', sa.Integer(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('dead_letter_count', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_source', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=260), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_external_at', sa.DateTime(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('raw_external_data_json', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=80), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=False),
    sa.Column('review_state', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_blog_external_source_id')
    )
    op.create_table('planned_content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('destinations_json', sa.Text(), nullable=False),
    sa.Column('goals_json', sa.Text(), nullable=False),
    sa.Column('product_ids_json', sa.Text(), nullable=False),
    sa.Column('selected_source_asset_ids_json', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=200), nullable=False),
    sa.Column('occasion', sa.String(length=200), nullable=False),
    sa.Column('promotion', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('brief_status', sa.String(length=80), nullable=False),
    sa.Column('last_production_run_at', sa.DateTime(), nullable=True),
    sa.Column('production_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('weekly_theme', sa.Text(), nullable=False),
    sa.Column('campaign_narrative', sa.Text(), nullable=False),
    sa.Column('validation_report_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('principals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_type', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('roles_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('secondary_audiences_json', sa.Text(), nullable=False),
    sa.Column('best_channels_json', sa.Text(), nullable=False),
    sa.Column('use_cases_json', sa.Text(), nullable=False),
    sa.Column('seasonality_json', sa.Text(), nullable=False),
    sa.Column('sales_momentum_note', sa.Text(), nullable=False),
    sa.Column('external_source', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=80), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=False),
    sa.Column('staleness_state', sa.String(length=80), nullable=False),
    sa.Column('manual_override_state', sa.String(length=80), nullable=False),
    sa.Column('manual_override_note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_path', sa.String(length=400), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('format', sa.String(length=120), nullable=False),
    sa.Column('source_path', sa.String(length=400), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_type', 'name', name='uq_template_type_name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=120), nullable=False),
    sa.Column('source_path', sa.String(length=400), nullable=False),
    sa.Column('preview_path', sa.String(length=400), nullable=False),
    sa.Column('platform_suitability_json', sa.Text(), nullable=False),
    sa.Column('readiness_state', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('external_source', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=80), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=False),
    sa.Column('staleness_state', sa.String(length=80), nullable=False),
    sa.Column('manual_override_state', sa.String(length=80), nullable=False),
    sa.Column('manual_override_note', sa.Text(), nullable=False),
    sa.Column('file_exists', sa.Integer(), nullable=False),
    sa.Column('file_checked_at', sa.DateTime(), nullable=True),
    sa.Column('file_modified_at', sa.DateTime(), nullable=True),
    sa.Column('file_checksum', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('asset_role', sa.String(length=120), nullable=False),
    sa.Column('rights', sa.String(length=80), nullable=False),
    sa.Column('brand_safe', sa.String(length=80), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('review_state', sa.String(length=80), nullable=False),
    sa.Column('approval_notes', sa.Text(), nullable=False),
    sa.Column('generated_prompt', sa.Text(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=True),
    sa.Column('default_reference', sa.Integer(), nullable=False),
    sa.Column('hidden_from_generation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=160), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_correlation', 'audit_events', ['correlation_id'], unique=False)
    op.create_index('ix_audit_events_created_type', 'audit_events', ['created_at', 'event_type'], unique=False)
    op.create_table('automation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=120), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=240), nullable=True),
    sa.Column('lease_owner', sa.String(length=160), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('last_error_code', sa.String(length=120), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_automation_jobs_claim', 'automation_jobs', ['state', 'scheduled_at', 'priority', 'id'], unique=False)
    op.create_index('ix_automation_jobs_correlation', 'automation_jobs', ['correlation_id'], unique=False)
    op.create_index('ix_automation_jobs_lease', 'automation_jobs', ['state', 'lease_expires_at'], unique=False)
    op.create_table('calendar_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=260), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('business_goal', sa.String(length=160), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.String(length=160), nullable=False),
    sa.Column('featured_product', sa.String(length=200), nullable=False),
    sa.Column('draft_copy', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('hashtags_json', sa.Text(), nullable=False),
    sa.Column('asset_brief', sa.Text(), nullable=False),
    sa.Column('asset_type', sa.String(length=120), nullable=False),
    sa.Column('production_notes', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('effort_estimate', sa.String(length=40), nullable=False),
    sa.Column('expected_impact', sa.String(length=40), nullable=False),
    sa.Column('success_metric', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etsy_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('external_source', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=220), nullable=False),
    sa.Column('shop_id', sa.String(length=160), nullable=False),
    sa.Column('listing_id', sa.String(length=160), nullable=False),
    sa.Column('transaction_id', sa.String(length=160), nullable=False),
    sa.Column('buyer_user_id', sa.String(length=160), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('image_url_fullxfull', sa.String(length=500), nullable=False),
    sa.Column('created_timestamp', sa.Integer(), nullable=True),
    sa.Column('updated_timestamp', sa.Integer(), nullable=True),
    sa.Column('raw_data_json', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_etsy_review_source_id')
    )
    op.create_table('generated_content_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_item_id', sa.Integer(), nullable=False),
    sa.Column('candidate_type', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_facts_json', sa.Text(), nullable=False),
    sa.Column('source_asset_ids_json', sa.Text(), nullable=False),
    sa.Column('review_state', sa.String(length=80), nullable=False),
    sa.Column('revision_notes', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planned_item_id'], ['planned_content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planned_item_id', 'candidate_type', 'provider', name='uq_candidate_planned_type_provider')
    )
    op.create_table('operator_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=240), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=128), nullable=False),
    sa.Column('remote_address_hash', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash')
    )
    op.create_index('ix_operator_sessions_expiry', 'operator_sessions', ['idle_expires_at', 'absolute_expires_at'], unique=False)
    op.create_index('ix_operator_sessions_principal_active', 'operator_sessions', ['principal_id', 'revoked_at'], unique=False)
    op.create_table('product_external_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=260), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'external_id', name='uq_product_external_source_id')
    )
    op.create_table('product_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=220), nullable=False),
    sa.Column('listing_id', sa.String(length=160), nullable=False),
    sa.Column('listing_title', sa.String(length=260), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('revenue_cents', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=12), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data_json', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'external_id', name='uq_product_sales_source_id')
    )
    op.create_table('service_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('token_prefix', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('token_prefix')
    )
    op.create_table('creative_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=False),
    sa.Column('candidate_asset_id', sa.Integer(), nullable=True),
    sa.Column('target_format', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('requested_dimensions', sa.String(length=80), nullable=False),
    sa.Column('provider_job_id', sa.String(length=200), nullable=False),
    sa.Column('provider_status', sa.String(length=80), nullable=False),
    sa.Column('provider_error', sa.Text(), nullable=False),
    sa.Column('output_url', sa.String(length=500), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=False),
    sa.Column('response_metadata_json', sa.Text(), nullable=False),
    sa.Column('review_state', sa.String(length=80), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('calendar_item_id', sa.Integer(), nullable=True),
    sa.Column('planned_content_item_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=260), nullable=False),
    sa.Column('owner_role', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('generated_content_candidate_id', sa.Integer(), nullable=True),
    sa.Column('draft_caption', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('hashtags_json', sa.Text(), nullable=False),
    sa.Column('posting_steps_json', sa.Text(), nullable=False),
    sa.Column('preview_checklist_json', sa.Text(), nullable=False),
    sa.Column('metric_instruction', sa.Text(), nullable=False),
    sa.Column('published_url', sa.String(length=500), nullable=False),
    sa.Column('platform_post_id', sa.String(length=160), nullable=False),
    sa.Column('metric_due_date', sa.Date(), nullable=True),
    sa.Column('metric_status', sa.String(length=80), nullable=False),
    sa.Column('external_source', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=80), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=False),
    sa.Column('staleness_state', sa.String(length=80), nullable=False),
    sa.Column('manual_override_state', sa.String(length=80), nullable=False),
    sa.Column('manual_override_note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['calendar_item_id'], ['calendar_items.id'], ),
    sa.ForeignKeyConstraint(['generated_content_candidate_id'], ['generated_content_candidates.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['planned_content_item_id'], ['planned_content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('etsy_visits', sa.Integer(), nullable=True),
    sa.Column('etsy_orders', sa.Integer(), nullable=True),
    sa.Column('email_signups', sa.Integer(), nullable=True),
    sa.Column('outcome_tags_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('collection_status', sa.String(length=80), nullable=False),
    sa.Column('external_source', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=80), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=False),
    sa.Column('manual_override_state', sa.String(length=80), nullable=False),
    sa.Column('manual_override_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('tasks')
    op.drop_table('creative_generation_jobs')
    op.drop_table('service_credentials')
    op.drop_table('product_sales')
    op.drop_table('product_external_references')
    op.drop_index('ix_operator_sessions_principal_active', table_name='operator_sessions')
    op.drop_index('ix_operator_sessions_expiry', table_name='operator_sessions')
    op.drop_table('operator_sessions')
    op.drop_table('generated_content_candidates')
    op.drop_table('etsy_reviews')
    op.drop_table('calendar_items')
    op.drop_index('ix_automation_jobs_lease', table_name='automation_jobs')
    op.drop_index('ix_automation_jobs_correlation', table_name='automation_jobs')
    op.drop_index('ix_automation_jobs_claim', table_name='automation_jobs')
    op.drop_table('automation_jobs')
    op.drop_index('ix_audit_events_created_type', table_name='audit_events')
    op.drop_index('ix_audit_events_correlation', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('assets')
    op.drop_table('templates')
    op.drop_table('sync_metadata')
    op.drop_table('products')
    op.drop_table('principals')
    op.drop_table('plans')
    op.drop_table('planned_content_items')
    op.drop_table('blog_posts')
    op.drop_table('automation_runs')
    # ### end Alembic commands ###
