"""growth identity and feedback contracts

Revision ID: 0002_growth_contracts
Revises: 0001_service_foundation
Create Date: 2026-07-24 08:48:13.923096
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_growth_contracts'
down_revision: Union[str, None] = '0001_service_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.String(length=260), nullable=False),
    sa.Column('deduplication_key', sa.String(length=240), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=40), nullable=False),
    sa.Column('evidence_state', sa.String(length=40), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key')
    )
    op.create_index('ix_demand_evidence_source_time', 'demand_evidence', ['source_name', 'source_timestamp'], unique=False)
    op.create_index('ix_demand_evidence_topic_state', 'demand_evidence', ['topic', 'evidence_state'], unique=False)
    op.create_table('growth_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('campaign_id', sa.String(length=160), nullable=False),
    sa.Column('content_id', sa.String(length=160), nullable=False),
    sa.Column('publication_id', sa.String(length=160), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=160), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('attribution_quality', sa.String(length=40), nullable=False),
    sa.Column('destination_url', sa.String(length=500), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_growth_events_campaign_content', 'growth_events', ['campaign_id', 'content_id'], unique=False)
    op.create_index('ix_growth_events_type_source_time', 'growth_events', ['event_type', 'source_timestamp'], unique=False)
    op.create_table('product_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.String(length=160), nullable=True),
    sa.Column('website_slug', sa.String(length=220), nullable=False),
    sa.Column('etsy_listing_id', sa.String(length=160), nullable=True),
    sa.Column('mapping_state', sa.String(length=40), nullable=False),
    sa.Column('exception_reason', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etsy_listing_id', name='uq_product_identity_etsy_listing_id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('website_id', name='uq_product_identity_website_id')
    )
    op.create_index('ix_product_identities_mapping_state', 'product_identities', ['mapping_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_identities_mapping_state', table_name='product_identities')
    op.drop_table('product_identities')
    op.drop_index('ix_growth_events_type_source_time', table_name='growth_events')
    op.drop_index('ix_growth_events_campaign_content', table_name='growth_events')
    op.drop_table('growth_events')
    op.drop_index('ix_demand_evidence_topic_state', table_name='demand_evidence')
    op.drop_index('ix_demand_evidence_source_time', table_name='demand_evidence')
    op.drop_table('demand_evidence')
    # ### end Alembic commands ###
